### ISSUE TITLE
Readme is very cluttered

### ISSUE THREAD

**Issue by yogeshpaliyal** [yogeshpaliyal/Android-Universal-Recycler-View-Adapter#12]

**Comment by AaquibAli** [comment]
pls assign this isuue to me for my hacktoberfest contribution

**Comment by IamRaja007** [comment]
Hello Yogesh. I was wondering if you could give some description as to what has to be done exactly in this issue, so you know we can contribute better in quality.. Thanks!

**Comment by yogeshpaliyal** [comment]
Yes, Sure

It is a library of Recycler View Adapter which can show multiple states
like loading state, content listing, error state and no data state

**Comment by yogeshpaliyal** [comment]
You can ask me, if you have any doubts

**Comment by IamRaja007** [comment]
Okay! So what has to be done with the readme. As the issue says, "Readme is very cluttered", I wanted to know that what changes would you like to have in the Readme file, so that I can get a good clarity about this issue and work on it.

**Comment by yogeshpaliyal** [comment]
If you can write Readme in a manner that is easy to understand  other developers, it will be very useful

**Comment by IamRaja007** [comment]
Okay! Trying to work on this issue.. thanks!

**Comment by IamRaja007** [comment]
@yogeshpaliyal Sir, can you point out to me some points that should be in a good readme. Sorry, I have to ask again, actually I am still not getting what could be added or modified. Could you please help me understand clearly.
